# Generated by Django 4.2.21 on 2025-05-21 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('page_url', models.URLField()),
                ('page_username', models.CharField(blank=True, max_length=255, null=True)),
                ('page_category', models.CharField(blank=True, max_length=255, null=True)),
                ('page_website', models.URLField(blank=True, null=True)),
                ('page_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('page_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('page_address', models.TextField(blank=True, null=True)),
                ('page_number', models.CharField(blank=True, max_length=255, null=True)),
                ('page_country', models.CharField(blank=True, max_length=255, null=True)),
                ('page_description', models.TextField(blank=True, null=True)),
                ('page_followers', models.CharField(blank=True, max_length=255, null=True)),
                ('page_likes', models.CharField(blank=True, max_length=255, null=True)),
                ('page_talking_count', models.CharField(blank=True, max_length=255, null=True)),
                ('page_engagement', models.CharField(blank=True, max_length=255, null=True)),
                ('page_index', models.CharField(blank=True, max_length=255, null=True)),
                ('page_post_per_day', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PageInfo.pagegroup')),
            ],
        ),
    ]
