# Generated by Django 4.2.21 on 2025-05-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagegroup',
            name='url',
        ),
        migrations.AddField(
            model_name='pagegroup',
            name='group_name',
            field=models.CharField(default='Unnamed Group', max_length=255),
        ),
        migrations.DeleteModel(
            name='PageInfo',
        ),
    ]
