# Generated by Django 4.2.21 on 2025-05-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0002_remove_pagegroup_url_pagegroup_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagegroup',
            name='page_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PageInfo.pagegroup'),
        ),
        migrations.AlterField(
            model_name='pagegroup',
            name='group_name',
            field=models.CharField(default='Group1', max_length=255),
        ),
    ]
