# Generated by Django 4.2.21 on 2025-05-23 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0003_pagegroup_page_group_alter_pagegroup_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagegroup',
            name='page_group',
        ),
        migrations.AlterField(
            model_name='pagegroup',
            name='group_name',
            field=models.CharField(default='Unnamed Group', max_length=255),
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_url', models.URLField(blank=True, null=True)),
                ('followers', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('engagement', models.FloatField(default=0.0)),
                ('page_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='PageInfo.pagegroup')),
            ],
        ),
    ]
