# Generated by Django 4.2.21 on 2025-05-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0004_remove_pagegroup_page_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageinfo',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='likes',
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='is_business_page',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_likes_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_talking_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_were_here_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='page_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
