# Generated by Django 4.2.21 on 2025-05-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0005_remove_pageinfo_engagement_remove_pageinfo_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='page_followers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_followers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_likes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
